# Form implementation generated from reading ui file 'd:\Rain\source\repos\zhuiyiStation\app\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_K8s(object):
    def contextMenuEvent(self, e):
        menu = RoundMenu(parent=self)
        # menu = CheckableMenu(parent=self, indicatorType=MenuIndicatorType.CHECK)

        # NOTE: hide the shortcut key
        # menu.view.setItemDelegate(MenuItemDelegate())

        # add actions
        menu.addAction(Action(FIF.COPY, "Copy"))
        menu.addAction(Action(FIF.CUT, "Cut"))
        menu.actions()[0].setCheckable(True)
        menu.actions()[0].setChecked(True)

        # add sub menu
        submenu = RoundMenu("Add to", self)
        submenu.setIcon(FIF.ADD)
        submenu.addActions(
            [
                Action(FIF.VIDEO, "Video"),
                Action(FIF.MUSIC, "Music"),
            ]
        )
        menu.addMenu(submenu)

        # add actions
        menu.addActions([Action(FIF.PASTE, "Paste"), Action(FIF.CANCEL, "Undo")])

        # add separator
        menu.addSeparator()
        menu.addAction(QAction(f"Select all", shortcut="Ctrl+A"))

        # insert actions
        menu.insertAction(
            menu.actions()[-1], Action(FIF.SETTING, "Settings", shortcut="Ctrl+S")
        )
        menu.insertActions(
            menu.actions()[-1],
            [
                Action(FIF.HELP, "Help", shortcut="Ctrl+H"),
                Action(FIF.FEEDBACK, "Feedback", shortcut="Ctrl+F"),
            ],
        )
        menu.actions()[-2].setCheckable(True)
        menu.actions()[-2].setChecked(True)

        # show menu
        menu.exec(e.globalPos(), aniType=MenuAnimationType.DROP_DOWN)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form.resize(629, 350)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PodList = TableWidget(parent=Form)
        self.PodList.setBorderVisible(True)
        self.PodList.setBorderRadius(8)
        self.PodList.setMinimumSize(QtCore.QSize(400, 400))
        self.PodList.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff
        )
        self.PodList.setShowGrid(False)
        self.PodList.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.PodList.setSelectRightClickedRow(False)
        self.PodList.setObjectName("PodList")
        self.PodList.setColumnCount(5)
        self.PodList.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.PodList.setHorizontalHeaderItem(4, item)
        self.PodList.horizontalHeader().setVisible(True)
        self.PodList.horizontalHeader().setCascadingSectionResizes(False)
        self.PodList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.PodList)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.PodList.verticalHeaderItem(0)
        item.setText(_translate("Form", "新建行"))
        item = self.PodList.verticalHeaderItem(1)
        item.setText(_translate("Form", "新建行"))
        item = self.PodList.verticalHeaderItem(2)
        item.setText(_translate("Form", "新建行"))
        item = self.PodList.verticalHeaderItem(3)
        item.setText(_translate("Form", "新建行"))
        item = self.PodList.verticalHeaderItem(4)
        item.setText(_translate("Form", "新建行"))
        item = self.PodList.horizontalHeaderItem(0)
        item.setText(_translate("Form", "新建列"))
        item = self.PodList.horizontalHeaderItem(1)
        item.setText(_translate("Form", "新建列"))
        item = self.PodList.horizontalHeaderItem(2)
        item.setText(_translate("Form", "新建列"))
        item = self.PodList.horizontalHeaderItem(3)
        item.setText(_translate("Form", "新建列"))
        item = self.PodList.horizontalHeaderItem(4)
        item.setText(_translate("Form", "新建列"))


from qfluentwidgets import (
    TableWidget,
    RoundMenu,
    Action,
    MenuAnimationType,
    MenuItemDelegate,
    CheckableMenu,
    MenuIndicatorType,
)
from qfluentwidgets import FluentIcon as FIF
from PyQt6.QtGui import QAction
